
#line 3 "cfg_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = (yy_hold_char); \
    	YY_RESTORE_YY_MORE_OFFSET \
        (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
    	YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
    {
	FILE *yy_input_file;

	char *yy_ch_buf;        /* input buffer */
	char *yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
	int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
	int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
	int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
	int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2

    };
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;        /* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;        /* whether we need to initialize */
static int yy_start = 0;    /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
    	YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
    } \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
    	YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
    } \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    (yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    (yy_hold_char) = *yy_cp; \
    *yy_cp = '\0'; \
    (yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
    {
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
    };
static yyconst flex_int16_t yy_accept[501] =
    {   0,
        0,    0,   74,   72,    2,    1,   72,   72,   71,    7,
        6,   71,   69,   69,   71,   71,   68,   68,   71,   71,
       71,   71,   69,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   68,   71,   71,    4,    5,    1,    0,
       70,    0,    0,    0,    0,    0,    0,    0,    3,   71,
        8,    7,   71,   69,   71,   68,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   69,
        0,    0,    0,    0,   68,    0,    0,   71,   69,   71,

       71,   71,   68,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   12,
       71,   13,   71,   71,   71,    0,    0,    0,    0,   71,
       71,   71,   68,   71,   71,   53,   71,   71,   71,   71,
       71,   50,   71,   71,   71,   71,   71,   71,   51,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   27,   71,   71,    0,    0,   69,   15,   71,
       71,   71,   71,   71,   71,   71,   71,   28,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   11,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,    0,    0,   71,   71,   71,   26,   71,   31,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   29,   71,   71,   71,   16,   17,
       18,   19,   71,   10,   24,   20,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   60,   71,   48,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   23,   71,   71,   71,   71,    9,   71,
       71,   71,   71,   71,   59,   71,   71,   71,   71,   37,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   32,   71,   71,   71,   71,
       25,   71,   45,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   36,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       46,   71,   71,   71,   71,   21,   71,   71,   14,   71,
       39,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   66,   38,   71,   71,   71,   71,   71,   71,
       71,   71,   33,   71,   71,   44,   71,   71,   71,   71,

       71,   71,   61,   71,   42,   71,   43,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   56,
       71,   71,   47,   62,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   54,   71,   71,   71,   71,   71,
       71,   71,   71,   34,   35,   71,   67,   71,   71,   71,
       71,   71,   65,   71,   71,   71,   71,   30,   71,   71,
       57,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   64,   49,   71,   71,   52,   71,
       55,   71,   71,   71,   71,   71,   71,   63,   71,   71,
       71,   71,   71,   71,   58,   22,   41,   71,   40,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    1,    8,    9,   10,
       11,   12,   12,   12,   12,   12,   12,    1,    1,    1,
       13,    1,    1,    1,   14,   15,   15,   15,   16,   17,
       15,   15,   15,   15,   15,   18,   15,   19,   20,   15,
       15,   21,   22,   23,   24,   15,   15,   15,   25,   15,
        1,   26,    1,    1,    1,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   15,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    3,    3,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[505] =
    {   0,
        0,    0,  615,  616,  616,    0,   50,  611,   47,   52,
      616,    0,   51,   46,   55,  591,   50,   61,  575,  584,
       49,  583,   71,  566,  568,  576,  566,  578,   80,   70,
      558,   71,   77,   83,  559,   48,  616,  616,    0,   77,
      616,  103,  111,  121,  118,  119,  599,  598,  616,    0,
      146,  154,  106,    0,  101,    0,  582,  577,  122,  126,
      557,  568,  553,  552,  553,  562,  552,  551,  546,  558,
      555,  542,  542,  547,  554,  540,  101,  547,  552,  541,
      128,  552,  543,  540,  532,  531,  543,  530,  537,  616,
      155,  145,  165,  148,  616,  172,  173,  156,    0,  524,

      523,  159,    0,  530,  532,  522,  526,  531,  526,  524,
      516,  516,  519,  553,  529,  516,  550,  523,  509,  521,
      505,  502,  519,  502,  515,  517,  502,  502,  538,  537,
      505,  535,  497,  503,  493,  179,  176,  190,  181,  172,
      526,  527,    0,  529,   97,    0,  494,  502,  492,  486,
      489,    0,  502,  147,  494,  521,  157,  491,    0,  494,
      497,  473,  477,  515,  514,  513,  483,  486,  477,  177,
      475,  473,    0,  482,  481,  206,  189,    0,    0,  504,
      469,  470,  468,  462,  463,  466,  473,    0,  466,  467,
      470,  494,  183,  464,  463,  460,  453,  450,  488,    0,

      465,  184,  464,  451,  460,  449,  449,  460,  453,  442,
      441,  477,  205,  225,  439,  451,  447,    0,  435,    0,
      439,  442,  439,  428,  441,  433,  437,  440,  439,  426,
      431,  436,  460,  434,  179,  418,  436,  425,  415,  421,
      453,  420,  424,  417,  449,  414,  409,  184,  616,  616,
      616,  616,  412,  445,    0,    0,  420,  402,  417,  416,
      409,  406,  401,  195,  400,  436,  410,    0,  396,  433,
      395,  400,  404,  390,  394,  401,  426,  402,  403,  394,
      398,  395,  381,    0,  384,  381,  378,  200,    0,  391,
      382,  383,  379,  379,    0,  374,  375,  380,  381,    0,

      382,  376,  371,  363,  365,  381,  362,  362,  376,  377,
      358,  363,  357,  373,  359,    0,  358,  357,  356,  364,
        0,  367,    0,  365,  361,  360,  384,  357,  351,  344,
      355,  336,    0,  349,  377,  338,  346,  353,  350,  349,
      346,  342,  346,  330,  324,  328,  332,  338,  331,  341,
      338,  322,  206,  315,  324,  316,  312,  311,  309,  322,
        0,  307,  328,  322,  321,    0,  327,  318,    0,  302,
        0,  312,  307,  318,  311,  302,  312,  310,  306,  337,
      314,  310,    0,    0,  309,  308,  307,  303,  305,  329,
      298,  296,  326,  300,  299,    0,  323,  322,  321,  289,

      285,  280,    0,  280,    0,  283,    0,  290,  314,  292,
      287,  282,  269,  286,  270,  284,  267,  276,  279,    0,
      264,  302,    0,    0,  205,  279,  300,  260,  235,  259,
      269,  271,  263,  261,    0,  272,  269,  265,  261,  264,
      254,  248,  242,    0,    0,  285,    0,  247,  249,  243,
      246,  251,    0,  241,  253,  240,  247,    0,  236,  235,
        0,  248,  241,  236,  231,  232,  229,  235,  237,  227,
      227,  238,  234,  236,    0,    0,  235,  227,    0,  217,
        0,  232,  223,  221,  222,  223,  206,    0,  202,  207,
      204,  160,  141,   96,    0,    0,    0,   51,    0,  616,

      251,  254,  257,   76
    } ;

static yyconst flex_int16_t yy_def[505] =
    {   0,
      500,    1,  500,  500,  500,  501,  502,  503,  504,  504,
      500,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  500,  500,  501,  502,
      500,  502,  502,  502,  502,  502,  502,  503,  500,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  500,
      502,  502,  502,  502,  500,  502,  502,  504,  504,  504,

      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  502,  502,  502,  502,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  502,  502,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,

      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  502,  500,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  500,  500,
      500,  500,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,

      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,

      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,    0,

      500,  500,  500,  500
    } ;

static yyconst flex_uint16_t yy_nxt[670] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   10,   10,
       10,   10,   11,   12,   12,   12,   13,   12,   14,   15,
       12,   16,   17,   12,   18,    4,   19,   20,   21,   22,
       12,   23,   24,   25,   12,   26,   27,   28,   14,   29,
       30,   31,   32,   33,   34,   35,   12,   36,   12,   18,
       12,   37,   38,   41,   51,   51,   51,   51,   51,   52,
       52,   52,   52,   52,   53,   54,   42,   58,   43,   44,
       59,   55,   45,   56,   46,   47,   60,   53,   50,   63,
       41,   42,   64,   65,   53,   54,   55,   88,   43,   44,
       89,   60,   59,   56,   45,  499,   55,   53,   56,   46,

       74,   79,   47,   59,   75,   80,   90,   81,   73,   76,
       82,   55,   77,   67,   90,   83,   91,   99,   56,   86,
       84,   95,   95,   98,   41,   59,   85,  182,   47,   91,
       92,  120,   99,  183,   97,  121,   47,   93,   96,   94,
      122,  498,   98,   47,   47,  102,   47,  103,   90,   97,
       92,   95,   93,   51,   51,   51,   51,   51,   41,   94,
       96,   52,   52,   52,   52,   52,  126,  102,   41,  103,
       47,  127,  136,   47,  143,   41,   41,  140,  190,   90,
       47,  137,   41,  191,   95,  497,  194,  178,  195,  143,
       47,  136,   95,   41,  139,  138,  137,   47,   47,  140,

      176,   47,  178,  496,   47,  177,   47,  207,   90,   41,
      208,  226,  227,  237,   47,   47,  139,  138,  285,  271,
      177,  213,  176,  272,  286,  228,  296,  238,  319,  229,
       47,   47,  249,  250,  251,  252,  213,  378,  297,  438,
      495,  439,  320,  444,  445,  440,  494,  493,  492,  491,
      379,   39,  490,   39,   40,   40,   40,   48,   48,   48,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,

      449,  448,  447,  446,  443,  442,  441,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,

      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  236,  235,  234,  233,  232,  231,  230,  225,

      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  212,  211,  210,  209,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  193,  192,  189,  188,
      187,  186,  185,  184,  181,  180,  179,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  142,
      141,  135,  134,  133,  132,  131,  130,  129,  128,  125,
      124,  123,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  101,  100,

       49,  500,   87,   78,   72,   71,   70,   69,   68,   66,
       62,   61,   57,   49,  500,    3,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500
    } ;

static yyconst flex_int16_t yy_chk[670] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    9,    9,    9,    9,    9,   10,
       10,   10,   10,   10,   13,   14,    7,   17,    7,    7,
       17,   15,    7,   15,    7,    7,   18,   13,  504,   21,
       40,    7,   21,   21,   23,   14,   15,   36,    7,    7,
       36,   18,   17,   15,    7,  498,   29,   23,   29,    7,

       30,   32,   40,   34,   30,   32,   42,   33,   29,   30,
       33,   29,   30,   23,   43,   33,   42,   55,   29,   34,
       33,   45,   46,   53,   44,   34,   33,  145,   42,   42,
       43,   77,   55,  145,   46,   77,   43,   44,   45,   44,
       77,  494,   53,   45,   46,   59,   44,   60,   92,   46,
       43,   94,   44,   51,   51,   51,   51,   51,   91,   44,
       45,   52,   52,   52,   52,   52,   81,   59,   93,   60,
       92,   81,   91,   94,  102,   96,   97,   98,  154,  137,
       91,   93,  136,  154,  139,  493,  157,  140,  157,  102,
       93,   91,  177,  138,   97,   96,   93,   96,   97,   98,

      136,  137,  140,  492,  136,  138,  139,  170,  213,  176,
      170,  193,  193,  202,  177,  138,   97,   96,  248,  235,
      138,  176,  136,  235,  248,  193,  264,  202,  288,  193,
      213,  176,  214,  214,  214,  214,  176,  353,  264,  425,
      491,  425,  288,  429,  429,  425,  490,  489,  487,  486,
      353,  501,  485,  501,  502,  502,  502,  503,  503,  503,
      484,  483,  482,  480,  478,  477,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  460,
      459,  457,  456,  455,  454,  452,  451,  450,  449,  448,
      446,  443,  442,  441,  440,  439,  438,  437,  436,  434,

      433,  432,  431,  430,  428,  427,  426,  422,  421,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  406,  404,  402,  401,  400,  399,  398,  397,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  370,  368,  367,  365,  364,  363,  362,  360,  359,
      358,  357,  356,  355,  354,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  322,  320,  319,  318,  317,  315,  314,

      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  299,  298,  297,  296,  294,  293,  292,
      291,  290,  287,  286,  285,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      267,  266,  265,  263,  262,  261,  260,  259,  258,  257,
      254,  253,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  219,  217,
      216,  215,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  201,  199,  198,  197,  196,  195,  194,  192,

      191,  190,  189,  187,  186,  185,  184,  183,  182,  181,
      180,  175,  174,  172,  171,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  158,  156,  155,  153,  151,
      150,  149,  148,  147,  144,  142,  141,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  101,
      100,   89,   88,   87,   86,   85,   84,   83,   82,   80,
       79,   78,   76,   75,   74,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   61,   58,   57,

       48,   47,   35,   31,   28,   27,   26,   25,   24,   22,
       20,   19,   16,    8,    3,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cfg_lex.l"
#line 2 "cfg_lex.l"
#include <stdio.h>
#include <assert.h>

#include "configuration.h"
#include "cfg_parser.h"

char input_line[512];

#define YY_NO_INPUT 1
#line 803 "cfg_lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

        	int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
        { \
    	int c = '*'; \
    	size_t n; \
    	for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
        	buf[n] = (char) c; \
    	if ( c == '\n' ) \
        	buf[n++] = (char) c; \
    	if ( c == EOF && ferror( yyin ) ) \
        	YY_FATAL_ERROR( "input in flex scanner failed" ); \
    	result = n; \
        } \
	else \
        { \
    	errno=0; \
    	while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
            { \
        	if( errno != EINTR) \
                { \
            	YY_FATAL_ERROR( "input in flex scanner failed" ); \
            	break; \
                } \
        	errno=0; \
        	clearerr(yyin); \
            } \
        }\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
        {
        (yy_init) = 1;

#ifdef YY_USER_INIT
    	YY_USER_INIT;
#endif

    	if ( ! (yy_start) )
            (yy_start) = 1;    /* first start state */

    	if ( ! yyin )
        	yyin = stdin;

    	if ( ! yyout )
        	yyout = stdout;

    	if ( ! YY_CURRENT_BUFFER ) {
        	yyensure_buffer_stack ();
        	YY_CURRENT_BUFFER_LVALUE =
            	yy_create_buffer(yyin,YY_BUF_SIZE );
        }

    	yy_load_buffer_state( );
        }

    {
#line 15 "cfg_lex.l"

#line 1021 "cfg_lex.c"

	while ( /*CONSTCOND*/1 )        /* loops until end-of-file is reached */
        {
    	yy_cp = (yy_c_buf_p);

        /* Support of yytext. */
        *yy_cp = (yy_hold_char);

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
    	yy_bp = yy_cp;

    	yy_current_state = (yy_start);
yy_match:
    	do
            {
        	YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
        	if ( yy_accept[yy_current_state] )
                {
                (yy_last_accepting_state) = yy_current_state;
                (yy_last_accepting_cpos) = yy_cp;
                }
        	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
            	yy_current_state = (int) yy_def[yy_current_state];
            	if ( yy_current_state >= 501 )
                	yy_c = yy_meta[(unsigned int) yy_c];
                }
        	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
            ++yy_cp;
            }
    	while ( yy_base[yy_current_state] != 616 );

yy_find_action:
    	yy_act = yy_accept[yy_current_state];
    	if ( yy_act == 0 )
            { /* have to back up */
        	yy_cp = (yy_last_accepting_cpos);
        	yy_current_state = (yy_last_accepting_state);
        	yy_act = yy_accept[yy_current_state];
            }

    	YY_DO_BEFORE_ACTION;

    	if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
            {
        	int yyl;
        	for ( yyl = 0; yyl < yyleng; ++yyl )
            	if ( yytext[yyl] == '\n' )
                    
    yylineno++;
;
            }

do_action:    /* This label is used only to access EOF actions. */

    	switch ( yy_act )
    { /* beginning of action switch */
        	case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = (yy_hold_char);
        	yy_cp = (yy_last_accepting_cpos);
        	yy_current_state = (yy_last_accepting_state);
        	goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "cfg_lex.l"
{
	strncpy(input_line, yytext + 1, sizeof (input_line) - 1);
	input_line[sizeof(input_line) - 1] = '\0';
	yyless(1);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 21 "cfg_lex.l"
;
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 22 "cfg_lex.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "cfg_lex.l"
{ return ('{'); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "cfg_lex.l"
{ return ('}'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "cfg_lex.l"
{ return ('='); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "cfg_lex.l"
{
	yylval.i = atoi(yytext);
	return (UINT);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "cfg_lex.l"
{
	yylval.i = atoi(yytext);
	return (INT);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "cfg_lex.l"
{ return (TOK_FRONTEND); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "cfg_lex.l"
{ return (TOK_BACKEND); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "cfg_lex.l"
{ return (TOK_QUIET); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "cfg_lex.l"
{ return (TOK_SSL); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "cfg_lex.l"
{ return (TOK_TLS); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "cfg_lex.l"
{ return (TOK_TLS_PROTOS); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "cfg_lex.l"
{ return (TOK_SSLv3); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "cfg_lex.l"
{ return (TOK_TLSv1_0); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "cfg_lex.l"
{ return (TOK_TLSv1_1); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "cfg_lex.l"
{ return (TOK_TLSv1_2); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "cfg_lex.l"
{ return (TOK_TLSv1_3); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "cfg_lex.l"
{ return (TOK_CIPHERS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "cfg_lex.l"
{ return (TOK_SSL_ENGINE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "cfg_lex.l"
{ return (TOK_PREFER_SERVER_CIPHERS); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "cfg_lex.l"
{ return (TOK_WORKERS); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "cfg_lex.l"
{ return (TOK_BACKLOG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "cfg_lex.l"
{ return (TOK_KEEPALIVE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "cfg_lex.l"
{ return (TOK_CHROOT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "cfg_lex.l"
{ return (TOK_USER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "cfg_lex.l"
{ return (TOK_GROUP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "cfg_lex.l"
{ return (TOK_SYSLOG); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "cfg_lex.l"
{ return (TOK_SYSLOG_FACILITY); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "cfg_lex.l"
{ return (TOK_DAEMON); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "cfg_lex.l"
{ return (TOK_WRITE_IP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "cfg_lex.l"
{ return (TOK_WRITE_PROXY); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "cfg_lex.l"
{ return (TOK_WRITE_PROXY_V1); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "cfg_lex.l"
{ return (TOK_WRITE_PROXY_V2); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "cfg_lex.l"
{ return (TOK_PROXY_TLV); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "cfg_lex.l"
{ return (TOK_PEM_FILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "cfg_lex.l"
{ return (TOK_PROXY_PROXY); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "cfg_lex.l"
{ return (TOK_ALPN_PROTOS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "cfg_lex.l"
{ return (TOK_BACKEND_CONNECT_TIMEOUT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "cfg_lex.l"
{ return (TOK_SSL_HANDSHAKE_TIMEOUT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "cfg_lex.l"
{ return (TOK_RECV_BUFSIZE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "cfg_lex.l"
{ return (TOK_SEND_BUFSIZE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "cfg_lex.l"
{ return (TOK_LOG_FILENAME); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "cfg_lex.l"
{ return (TOK_LOG_LEVEL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "cfg_lex.l"
{ return (TOK_RING_SLOTS); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "cfg_lex.l"
{ return (TOK_RING_DATA_LEN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "cfg_lex.l"
{ return (TOK_PIDFILE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "cfg_lex.l"
{ return (TOK_SNI_NOMATCH_ABORT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "cfg_lex.l"
{ return (TOK_HOST); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "cfg_lex.l"
{ return (TOK_PORT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "cfg_lex.l"
{ return (TOK_MATCH_GLOBAL); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "cfg_lex.l"
{ return (TOK_PB_CERT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "cfg_lex.l"
{ return (TOK_PB_OCSP_FILE); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "cfg_lex.l"
{ return (TOK_OCSP_VERIFY); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "cfg_lex.l"
{ return (TOK_OCSP_RESP_TMO); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "cfg_lex.l"
{ return (TOK_OCSP_CONN_TMO); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "cfg_lex.l"
{ return (TOK_OCSP_REFRESH_INTERVAL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "cfg_lex.l"
{ return (TOK_OCSP_DIR); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "cfg_lex.l"
{ return (TOK_PEM_DIR); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "cfg_lex.l"
{ return (TOK_PEM_DIR_GLOB); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "cfg_lex.l"
{ return (TOK_SESSION_CACHE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "cfg_lex.l"
{ return (TOK_SHARED_CACHE_LISTEN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "cfg_lex.l"
{ return (TOK_SHARED_CACHE_PEER); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "cfg_lex.l"
{ return (TOK_SHARED_CACHE_IF); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "cfg_lex.l"
{ return (TOK_PRIVATE_KEY); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 95 "cfg_lex.l"
{ return (TOK_BACKEND_REFRESH); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 97 "cfg_lex.l"
{
	yylval.i = 1;
	return (BOOL);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "cfg_lex.l"
{
	yylval.i = 0;
	return (BOOL);
}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 107 "cfg_lex.l"
{
	char *s;
	if (strlen(yytext) == 2) {
    	yylval.s = NULL;
    	return (STRING);
    }
	s = strchr(yytext + 1, '"');
    *s = '\0';
	yylval.s = yytext + 1;
	return (STRING);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 118 "cfg_lex.l"
{
	yylval.s = yytext;
	return (STRING);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "cfg_lex.l"
;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "cfg_lex.l"
ECHO;
	YY_BREAK
#line 1488 "cfg_lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
    	int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = (yy_hold_char);
    	YY_RESTORE_YY_MORE_OFFSET

    	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between YY_CURRENT_BUFFER and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
        	YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
        	YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
    	if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
            { /* This was really a NUL. */
        	yy_state_type yy_next_state;

            (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

        	yy_current_state = yy_get_previous_state(  );

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

        	yy_next_state = yy_try_NUL_trans( yy_current_state );

        	yy_bp = (yytext_ptr) + YY_MORE_ADJ;

        	if ( yy_next_state )
                {
                /* Consume the NUL. */
            	yy_cp = ++(yy_c_buf_p);
            	yy_current_state = yy_next_state;
            	goto yy_match;
                }

        	else
                {
            	yy_cp = (yy_c_buf_p);
            	goto yy_find_action;
                }
            }

    	else switch ( yy_get_next_buffer(  ) )
            {
        	case EOB_ACT_END_OF_FILE:
                {
                (yy_did_buffer_switch_on_eof) = 0;

            	if ( yywrap( ) )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

                	yy_act = YY_STATE_EOF(YY_START);
                	goto do_action;
                    }

            	else
                    {
                	if ( ! (yy_did_buffer_switch_on_eof) )
                    	YY_NEW_FILE;
                    }
            	break;
                }

        	case EOB_ACT_CONTINUE_SCAN:
                (yy_c_buf_p) =
                    (yytext_ptr) + yy_amount_of_matched_text;

            	yy_current_state = yy_get_previous_state(  );

            	yy_cp = (yy_c_buf_p);
            	yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            	goto yy_match;

        	case EOB_ACT_LAST_MATCH:
                (yy_c_buf_p) =
                &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

            	yy_current_state = yy_get_previous_state(  );

            	yy_cp = (yy_c_buf_p);
            	yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            	goto yy_find_action;
            }
    	break;
        }

	default:
    	YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
    	YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
    	if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
        	return EOB_ACT_END_OF_FILE;
            }

    	else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
        	return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
    	YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
        {
        	int num_to_read =
        	YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

    	while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
        	YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

        	int yy_c_buf_p_offset =
                (int) ((yy_c_buf_p) - b->yy_ch_buf);

        	if ( b->yy_is_our_buffer )
                {
            	int new_size = b->yy_buf_size * 2;

            	if ( new_size <= 0 )
                	b->yy_buf_size += b->yy_buf_size / 8;
            	else
                	b->yy_buf_size *= 2;

            	b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                	yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
                }
        	else
                /* Can't grow it, we don't own it. */
            	b->yy_ch_buf = NULL;

        	if ( ! b->yy_ch_buf )
            	YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

        	num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                    	number_to_move - 1;

            }

    	if ( num_to_read > YY_READ_BUF_SIZE )
        	num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
    	YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
            (yy_n_chars), num_to_read );

    	YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
        }

	if ( (yy_n_chars) == 0 )
        {
    	if ( number_to_move == YY_MORE_ADJ )
            {
        	ret_val = EOB_ACT_END_OF_FILE;
        	yyrestart(yyin  );
            }

    	else
            {
        	ret_val = EOB_ACT_LAST_MATCH;
        	YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
            	YY_BUFFER_EOF_PENDING;
            }
        }

	else
    	ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
        /* Extend the array by 50%, plus the number we really need. */
    	int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
    	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
    	if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
        	YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
    }

    (yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

    (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
        {
    	YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
    	if ( yy_accept[yy_current_state] )
            {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
            }
    	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
        	yy_current_state = (int) yy_def[yy_current_state];
        	if ( yy_current_state >= 501 )
            	yy_c = yy_meta[(unsigned int) yy_c];
            }
    	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
        }

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
        {
        (yy_last_accepting_state) = yy_current_state;
        (yy_last_accepting_cpos) = yy_cp;
        }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
    	yy_current_state = (int) yy_def[yy_current_state];
    	if ( yy_current_state >= 501 )
        	yy_c = yy_meta[(unsigned int) yy_c];
        }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 500);

    	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
    *(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
    	if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
            /* This was really a NUL. */
            *(yy_c_buf_p) = '\0';

    	else
            { /* need more input */
        	int offset = (yy_c_buf_p) - (yytext_ptr);
            ++(yy_c_buf_p);

        	switch ( yy_get_next_buffer(  ) )
                {
            	case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                	yyrestart(yyin );

                    /*FALLTHROUGH*/

            	case EOB_ACT_END_OF_FILE:
                    {
                	if ( yywrap( ) )
                    	return 0;

                	if ( ! (yy_did_buffer_switch_on_eof) )
                    	YY_NEW_FILE;
#ifdef __cplusplus
                	return yyinput();
#else
                	return input();
#endif
                    }

            	case EOB_ACT_CONTINUE_SCAN:
                    (yy_c_buf_p) = (yytext_ptr) + offset;
                	break;
                }
            }
        }

	c = *(unsigned char *) (yy_c_buf_p);    /* cast for 8-bit char's */
    *(yy_c_buf_p) = '\0';    /* preserve yytext */
    (yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
        
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
    	YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
    }

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
    /* TODO. We should be able to replace this entire function body
     * with
     *    	yypop_buffer_state();
     *    	yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
    	return;

	if ( YY_CURRENT_BUFFER )
        {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
    	YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    	YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
        }

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
        (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
    (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
    	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
    	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
    	return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
    	YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
    	yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
    	return;

	b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
    	yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
    	return;

	yyensure_buffer_stack();

    /* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
        {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
    	YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    	YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
        }

    /* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
        (yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
    (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
    	return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
        --(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
    	yy_load_buffer_state( );
        (yy_did_buffer_switch_on_eof) = 1;
    }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

        /* First allocation is just for 2 elements, since we don't know if this
         * scanner will even need a stack. We use 2 instead of 1 to avoid an
         * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
        (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
                                (num_to_alloc * sizeof(struct yy_buffer_state*)
                                );
    	if ( ! (yy_buffer_stack) )
        	YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

    	memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

        (yy_buffer_stack_max) = num_to_alloc;
        (yy_buffer_stack_top) = 0;
    	return;
    }

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

        /* Increase the buffer to prepare for a possible push. */
    	yy_size_t grow_size = 8 /* arbitrary grow size */;

    	num_to_alloc = (yy_buffer_stack_max) + grow_size;
        (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
                                ((yy_buffer_stack),
                            	num_to_alloc * sizeof(struct yy_buffer_state*)
                                );
    	if ( ! (yy_buffer_stack) )
        	YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

        /* zero only the new slots.*/
    	memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
        (yy_buffer_stack_max) = num_to_alloc;
    }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
         base[size-2] != YY_END_OF_BUFFER_CHAR ||
         base[size-1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
    	return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
    	YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;    /* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
    /* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
    	YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
    	buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
    	YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
            (void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
    	yytext[yyleng] = (yy_hold_char); \
        (yy_c_buf_p) = yytext + yyless_macro_arg; \
        (yy_hold_char) = *(yy_c_buf_p); \
        *(yy_c_buf_p) = '\0'; \
    	yyleng = yyless_macro_arg; \
        } \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
    	yy_delete_buffer(YY_CURRENT_BUFFER  );
    	YY_CURRENT_BUFFER_LVALUE = NULL;
    	yypop_buffer_state();
    }

    /* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
    (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
        
	int i;
	for ( i = 0; i < n; ++i )
    	s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
        ;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
        	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
        
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
        	free( (char *) ptr );    /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 124 "cfg_lex.l"



